import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'

import Providers from '@/components/providers/Providers'
import { Toaster } from '@/components/ui/sonner'
import './globals.css'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Toaster position="top-right" richColors closeButton />
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
